apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: app1.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app1-src
                port:
                  number: 80
<<<<<<< HEAD
=======

>>>>>>> 3cd64d226e35efee7a072bb2553bd313237e6a43
    - host: app2.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app2-src
                port:
                  number: 80
<<<<<<< HEAD
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app3-src
                port:
                  number: 80
=======

  defaultBackend:
    service:
      name: app3-src
      port:
        number: 80
>>>>>>> 3cd64d226e35efee7a072bb2553bd313237e6a43
